language: node_js
node_js: 
  - "stable"
cache:
  directories:
    - "node_modules"
services:
  - postgresql

after_success: npm run coverage

before_script:
  - psql -c 'create database teamwork;' -U postgres
