const entertainment1 = `The first time I dreamt myself into the Marvel Cinematic Universe, I was Maria Hill. S.H.I.E.L.D. commander, human woman, competent as hell, possessed of both the righteous toys of war and the respect of Director Nicholas J. Fury to deploy them as needed, and unflappable in the face of galaxy-smashing chaos.
I cannot swear I was actually asleep when I slipped into her skin — possibly just drifting into hypnagogia during one of my many multi-day MCU binges — but with whatever faculties I could muster, I tried to remain there. Because when I wake, I am Mantis.`;

const entertainment2 = `We’re in a very interesting place in history where the time it takes to turn crisis into a movie script seems to be limited only by the presence of crisis. The 2008 financial free fall is an incredibly fertile ground from which to pluck both human and inhumane stories to present to a wider audience, often for the sake of assigning biographical blame. The Big Short and 99 Homes being more or less the two ends of Hollywood’s spectrum of takes on the Great Recession, the timeframe and its affect on the people in this country has implanted itself blatantly or subtly into a lot of the media we consume.`;

const business = `Looking at each Apple service on its own, it’s easy to compare them to similar rival services: Most of them are a commodity. A bundle would obfuscate that, but only to a certain degree. You still could compare it to said Amazon Prime or bundles from independent players.
Apple knows that — as of right now — their offering is not on pair on all fronts and therefore would need to feature a hefty discount. But where Apple has the monopoly (and high customer demand) is on hardware, namely the iPhone.`;

const productivity = `A lot of articles address the role of tech leads and engineering managers. One common theme we often come across is how to increase a team’s productivity. But before you focus your energy trying to increase their productivity, you might first want to consider what’s destroying it, to have a sound base on which you can build. Unfortunately, even though Peopleware was published almost 30 years ago, we see lots of teams suffering from huge productivity loss in some (negatively) remarkable ways!`;

const work = `As you would imagine, getting out of your chair and interrupting every person you see hard at work is a pretty scary idea and enough to make you doubt if it’s even worth doing.
As a matter of fact, Andrew, who really liked the idea initially, didn’t want to do it once we were at the coffee shop.
Once he saw that the first few people I talked to seemed to be delighted by our experiment, he grabbed his notepad and started asking questions as well (we included a surprising note on our experiment at the end of this article).
Nearly everyone we talked to told us that they too had always wondered what everyone else was doing.`;

const technology = `Blockchain is not only crappy technology but a bad vision for the future. Its failure to achieve adoption to date is because systems built on trust, norms, and institutions inherently function better than the type of no-need-for-trusted-parties systems blockchain envisions. That’s permanent: no matter how much blockchain improves it is still headed in the wrong direction.
This December I wrote a widely-circulated article on the inapplicability of blockchain to any actual problem. People objected mostly not to the technology argument, but rather hoped that decentralization could produce integrity.`;

const software = `Once you’ve set up your environment, and written your first Hello World program, continue to learn the basic, high-level concepts of your language. The code you write at this point will not be elegant, but you’ll create functioning programs while becoming acquainted with transferable fundamentals, such as typing and control flow, hence solving problems without having to simultaneously understand an insurmountable collection of concepts.`;

const family = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum`;

const health = `At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.`;

const relationships = `At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.`;

const travel = `At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas molestias excepturi sint occaecati cupiditate non provident, similique sunt in culpa qui officia deserunt mollitia animi, id est laborum et dolorum fuga. Et harum quidem rerum facilis est et expedita distinctio. Nam libero tempore, cum soluta nobis est eligendi optio cumque nihil impedit quo minus id quod maxime placeat facere possimus, omnis voluptas assumenda est, omnis dolor repellendus. Temporibus autem quibusdam et aut officiis debitis aut rerum necessitatibus saepe eveniet ut et voluptates repudiandae sint et molestiae non recusandae. Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis voluptatibus maiores alias consequatur aut perferendis doloribus asperiores repellat.`;

const education = `Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum`;

const politics = `Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?`;